name: Build Kairos Fleet

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'The base docker image to build from (e.g. ubuntu:24.04 or bring-your-own)'
        required: true
        type: string
      architecture:
        description: 'Target architecture'
        required: true
        type: choice
        options:
            - 'amd64'
            - 'arm64'
      model:
        description: 'Target model'
        required: true
        type: choice
        options:
            - 'generic'
            - 'rpi3'
            - 'nvidia-jetson-agx-orin'
      version:
        description: 'The Kairos version you want to define the image'
        type: string
        required: true
      kubernetes_distro:
        description: 'Kubernetes distribution'
        required: true
        default: ''
        type: choice
        options:
            - 'k3s'
            - 'k0s'
      kubernetes_version:
        description: 'Kubernetes version (depends on distro e.g. v1.33.3+k3s1)'
        required: true
        default: 'auto'
        type: string

jobs:
  kairos:
    name: Kairos Factory (bootable image)
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
    with:
      base_image: ${{ github.event.inputs.base_image }}
      arch: ${{ github.event.inputs.architecture }}
      model: ${{ github.event.inputs.model }}
      version: ${{ github.event.inputs.version }}
      iso: true
      grype: false
      summary_artifacts: true
      kubernetes_distro: ${{ github.event.inputs.kubernetes_distro }}
      kubernetes_version: ${{ github.event.inputs.kubernetes_version }}
